services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  tgbot:
    build: .
    command: bash -c "bin/rake telegram:bot:poller"
    volumes:
      - .:/chatbottg
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && RAILS_ENV=production bundle exec puma -C config/puma.rb"
    volumes:
      - .:/chatbottg
    ports:
      - "3000:3000"
    depends_on:
      - db
      - tgbot